/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-09-14 17:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class principal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      java.lang.String usuario = null;
      synchronized (session) {
        usuario = (java.lang.String) _jspx_page_context.getAttribute("usuario", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (usuario == null){
          usuario = new java.lang.String();
          _jspx_page_context.setAttribute("usuario", usuario, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>..::Menu Principal - JSP::..</title>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/estilo01.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/estilo03.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/estiloBuscar.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- cabecera -->\n");
      out.write("  <header>\n");
      out.write("      <img src=\"images/Pokemon_logo.svg.png\"/>\n");
      out.write("      <!-- Buscador -->\n");
      out.write("      <div id=\"buscador\">\n");
      out.write("          <form action=\"resultadoBusqueda.html\" method=\"get\">\n");
      out.write("              <fieldset> <!-- Agrupa items relacionados -->\n");
      out.write("                <legend>Buscador</legend> <!-- leged es el CAPTION para fieldset -->\n");
      out.write("                  <input type=\"search\" id=\"busqueda\" size=\"30\" placeholder=\"nombre del Pokemon\"/>\n");
      out.write("                  <div id=\"resultados\"></div>\n");
      out.write("              </fieldset>\n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("\t");
      out.print( usuario );
      out.write("\n");
      out.write("      </div> <!-- /buscador -->\n");
      out.write("\n");
      out.write("      <nav>\n");
      out.write("           <ul>\n");
      out.write("                <li><a href=\"/\">Inicio</a></li>\n");
      out.write("                <li><a href=\"#\">Nosotros</a></li>\n");
      out.write("                <li><a href=\"#\">Productos</a></li>\n");
      out.write("                <li><a href=\"#\">Contacto</a></li>\n");
      out.write("           </ul>\n");
      out.write("      </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <!-- Pie de página -->\n");
      out.write("  <footer>\n");
      out.write("      <p id=\"copyright\">&copy; 2016 By Dark Side</p>\n");
      out.write("  </footer> <!-- /pie de página -->\n");
      out.write("\n");
      out.write("  <script src=\"js/buscar.js\" ></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
